/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlarmImage: typeof import('./components/AlarmImage.vue')['default']
    AlarmLogsTable: typeof import('./components/AlarmLogsTable.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Device: typeof import('./components/Device.vue')['default']
    DeviceInteract: typeof import('./components/DeviceInteract.vue')['default']
    DevicesTable: typeof import('./components/DevicesTable.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    RfidTagsTable: typeof import('./components/RfidTagsTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
