/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/alarms/': RouteRecordInfo<'/alarms/', '/alarms', Record<never, never>, Record<never, never>>,
    '/devices/': RouteRecordInfo<'/devices/', '/devices', Record<never, never>, Record<never, never>>,
    '/devices/[id]': RouteRecordInfo<'/devices/[id]', '/devices/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/devices/configure': RouteRecordInfo<'/devices/configure', '/devices/configure', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/rfids/': RouteRecordInfo<'/rfids/', '/rfids', Record<never, never>, Record<never, never>>,
  }
}
